# Provision steps:
#
# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm install ingress-nginx ingress-nginx/ingress-nginx --version 4.0.18 --namespace kube-system --values ./ingress-nginx.yaml

rbac:
  create: true

controller:
  replicaCount: 2
  ingressClass: nginx

  config:
    enable-modsecurity: "false"
    enable-owasp-modsecurity-crs: "false"
    http2-max-field-size: 16k
    http2-max-header-size: 128k
    proxy-buffering: "on"
    proxy-buffers-number: "8"
    proxy-buffer-size: 32k

  service:
    externalTrafficPolicy: Local

  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - controller
            topologyKey: kubernetes.io/hostname
          weight: 100

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

defaultBackend:
  enabled: true
