name: terraform - test - azure/power-management

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.power-management.yml
      - azure/power-management/*.tf
      - azure/power-management/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.power-management.yml
      - azure/power-management/*.tf
      - azure/power-management/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/power-management
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
