name: terraform - test - github/repository

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.github.repository.yml
      - github/repository/*.tf
      - github/repository/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.github.repository.yml
      - github/repository/*.tf
      - github/repository/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: github/repository
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
