name: terraform - test - azure/linux-webapp

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.linux-webapp.yml
      - azure/linux-webapp/*.tf
      - azure/linux-webapp/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.linux-webapp.yml
      - azure/linux-webapp/*.tf
      - azure/linux-webapp/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/linux-webapp
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
