name: terraform - test - azure/terraform-ops

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.terraform-ops.yml
      - azure/terraform-ops/*.tf
      - azure/terraform-ops/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.terraform-ops.yml
      - azure/terraform-ops/*.tf
      - azure/terraform-ops/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/terraform-ops
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
