name: terraform - test - azure/container-registry

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.container-registry.yml
      - azure/container-registry/*.tf
      - azure/container-registry/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.container-registry.yml
      - azure/container-registry/*.tf
      - azure/container-registry/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/container-registry
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
