name: terraform - test - azure/kubernetes-service

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.kubernetes-service.yml
      - azure/kubernetes-service/*.tf
      - azure/kubernetes-service/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.kubernetes-service.yml
      - azure/kubernetes-service/*.tf
      - azure/kubernetes-service/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/kubernetes-service
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
