name: terraform - test - azure/bastion

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.bastion.yml
      - azure/bastion/*.tf
      - azure/bastion/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azure.bastion.yml
      - azure/bastion/*.tf
      - azure/bastion/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azure/bastion
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
