name: terraform - test - azuredevops/project

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azuredevops.project.yml
      - azuredevops/project/*.tf
      - azuredevops/project/*.hcl
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/tf.test.yml
      - .github/workflows/tf.test.azuredevops.project.yml
      - azuredevops/project/*.tf
      - azuredevops/project/*.hcl

jobs:
  test:
    uses: ./.github/workflows/tf.test.yml
    with:
      tf_path: azuredevops/project
      tf_version: latest
    permissions:
      contents: read
      checks: write
      pull-requests: write
